# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_line_mayne_stone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campion',
            options={'verbose_name_plural': 'Campion'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name_plural': 'Line'},
        ),
        migrations.AlterModelOptions(
            name='mayne',
            options={'verbose_name_plural': 'Mayne'},
        ),
        migrations.AlterModelOptions(
            name='stone',
            options={'verbose_name_plural': 'Stone'},
        ),
        migrations.AddField(
            model_name='campion',
            name='company_name',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='line',
            name='company_name',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='mayne',
            name='company_name',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='stone',
            name='company_name',
            field=models.CharField(default='Not entered', max_length=200),
        ),
    ]
