# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20170707_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Not entered', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='campion',
            name='company_name',
        ),
    ]
