# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20170707_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='campion',
            name='company_contact',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='campion',
            name='company_email',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='campion',
            name='company_name',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='campion',
            name='company_phone',
            field=models.CharField(default='Not entered', max_length=200),
        ),
    ]
