# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20170707_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campion',
            name='company_contact',
            field=models.CharField(default='eg. Helen Stephane', max_length=200),
        ),
    ]
