# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20170707_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='company_contact',
            field=models.CharField(default='eg. Helen Stephane', max_length=200),
        ),
        migrations.AddField(
            model_name='line',
            name='company_email',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='line',
            name='company_phone',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='mayne',
            name='company_contact',
            field=models.CharField(default='eg. Helen Stephane', max_length=200),
        ),
        migrations.AddField(
            model_name='mayne',
            name='company_email',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='mayne',
            name='company_phone',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='stone',
            name='company_contact',
            field=models.CharField(default='eg. Helen Stephane', max_length=200),
        ),
        migrations.AddField(
            model_name='stone',
            name='company_email',
            field=models.CharField(default='Not entered', max_length=200),
        ),
        migrations.AddField(
            model_name='stone',
            name='company_phone',
            field=models.CharField(default='Not entered', max_length=200),
        ),
    ]
