# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20170707_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campion',
            name='company_email',
            field=models.EmailField(default='Not entered', max_length=200),
        ),
        migrations.AlterField(
            model_name='line',
            name='company_email',
            field=models.EmailField(default='Not entered', max_length=200),
        ),
        migrations.AlterField(
            model_name='mayne',
            name='company_email',
            field=models.EmailField(default='Not entered', max_length=200),
        ),
        migrations.AlterField(
            model_name='stone',
            name='company_email',
            field=models.EmailField(default='Not entered', max_length=200),
        ),
    ]
