# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20170710_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campion',
            options={'ordering': ['student'], 'verbose_name_plural': 'Campion'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['student'], 'verbose_name_plural': 'Line'},
        ),
        migrations.AlterModelOptions(
            name='mayne',
            options={'ordering': ['student'], 'verbose_name_plural': 'Mayne'},
        ),
        migrations.AlterModelOptions(
            name='stone',
            options={'ordering': ['student'], 'verbose_name_plural': 'Stone'},
        ),
    ]
