# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_detail_date', models.DateField()),
                ('Work_detail', models.CharField(max_length=500)),
            ],
        ),
    ]
