# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('company_name', models.CharField(default='Not entered', max_length=200)),
                ('company_contact', models.CharField(default='eg. Helen Stephane', max_length=200)),
                ('company_phone', models.CharField(default='Not entered', max_length=200)),
                ('company_email', models.EmailField(default='Not entered', max_length=200)),
            ],
        ),
    ]
