# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='form_group',
            field=models.CharField(choices=[('CAMPION', 'Campion'), ('LINE', 'Line'), ('MAYNE', 'Mayne'), ('STONE', 'Stone')], default='CAMPION', max_length=7),
        ),
    ]
